### ISSUE TITLE
Invalid byte range.

### ISSUE THREAD

**Issue by moteus** [kikito/utf8_validator.lua#2]
Seems you have incorrect byte range in 
```Lua
elseif i == find(str, "[\194-\223][\123-\191]", i) then i = i + 2
```
`123` is `0x7B` but they defined as `C2..DF 80..BF`

**Comment by kikito** [comment]
It seems you are right. Do you want to send me a PR to fix this?

**Comment by kikito** [comment]
Nevermind, I did it myself. Thanks a lot for reporting this, and apologies if it caused you any trouble!
